#define PJ_CONFIG_IPHONE 1
#define PJSIP_TCP_TRANSPORT_DONT_CREATE_LISTENER 1
#define PJSIP_TLS_TRANSPORT_DONT_CREATE_LISTENER 1
#define PJ_HAS_IPV6 1
#define PJMEDIA_JBUF_DISC_MIN_GAP 1000
#define PJMEDIA_HAS_G7221_CODEC 1
#define PJMEDIA_JBUF_PRO_DISC_MAX_BURST 15
#include <pj/config_site_sample.h>
